from enum import StrEnum


class SystemToolName(StrEnum):
    LIST_USERS = "list_users"
    CREATE_USER = "create_user"
    INVITE_USER = "invite_user"
    UPDATE_USER_ACCESS = "update_user_access"
    LIST_API_KEYS = "list_api_keys"
    CREATE_API_KEY = "create_api_key"
    LIST_TARGETS = "list_targets"
    GET_TARGET_SCHEMA = "get_target_schema"
    LIST_OPERATIONS = "list_operations"
    REQUEST_OPERATION = "request_operation"
    LIST_MY_OPERATION_REQUESTS = "list_my_operation_requests"
    LIST_OPERATION_REQUESTS = "list_operation_requests"
    RESOLVE_OPERATION_REQUEST = "resolve_operation_request"
    CREATE_OPERATION = "create_operation"
    UPDATE_OPERATION = "update_operation"
    DISABLE_OPERATION = "disable_operation"
    GRANT_OPERATION = "grant_operation"
    REVOKE_OPERATION = "revoke_operation"
    LIST_OPERATION_GRANTS = "list_operation_grants"
    RELOAD_TOOLS = "reload_tools"
    EXECUTE = "execute"
